version: 0.1
species: Danio rerio
canonical_gene_id_type: Ensembl
include_gene_biotypes:
  - protein_coding
  - lincRNA
retain_duplicated_paralogs: true
fields:
  - token_id
  - species
  - gene_id
  - gene_symbol
  - gene_biotype
  - orthogroup_id
  - human_ortholog
  - is_protein_coding
  - is_testis_marker
  - is_germline_marker
  - is_somatic_marker
output_vocab_tsv: data/interim/zebrafish_vocab_v0_1.tsv
notes: "No silent collapse of teleost duplicated genes."
